apply plugin: 'java'

sourceCompatibility = '1.8'
targetCompatibility = '1.8'
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

if (!hasProperty('mainClass')) {
    ext.mainClass = 'com.api.Asparagus'
}

repositories {
    mavenCentral()
}

dependencies {
    // Spark Java
    implementation 'com.sparkjava:spark-core:2.9.4'
    
    // Log4j 1.x bridge -> Log4j2 (secure log4j 1.2 API compatible implementation)
    implementation 'org.apache.logging.log4j:log4j-1.2-api:2.24.3'
    implementation 'org.apache.logging.log4j:log4j-core:2.24.3'
    
    // RabbitMQ AMQP Client
    implementation 'com.rabbitmq:amqp-client:5.25.0'

    // Hibernate ORM & SQLite Driver
    implementation 'org.hibernate:hibernate-core:5.6.15.Final'
    implementation 'org.xerial:sqlite-jdbc:3.49.1.0'

    
    // Google Gson
    implementation 'com.google.code.gson:gson:2.12.1'
    
    // Spymemcached
    implementation 'net.spy:spymemcached:2.12.3'

    // JAXB for Java 11+ runtime compatibility
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.9'

    // Testing
    testImplementation 'junit:junit:4.13.2'
}

task initDb(type: JavaExec) {
    mainClass = 'com.util.DatabaseInitializer'
    classpath = sourceSets.main.runtimeClasspath
}

